---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-9.0

suites:
  - name: default
    run_list:
      - recipe[aw_dnsmasq::default]
    attributes:
      aw_dnsmasq:
        domain: test
